//
//  SheetAnimations_GameDevHelperAPI_RandomFrames.cpp
//  SpriteHelper2-TestCases
//
//  Created by Bogdan Vladu on 5/22/13.
//
//

#include "SheetAnimations_GameDevHelperAPI_RandomFrames.h"
#include "HelloWorldScene.h"

using namespace cocos2d;

SheetAnimations_GameDevHelperAPI_RandomFrames::~SheetAnimations_GameDevHelperAPI_RandomFrames()
{
	// cpp don't need to call super dealloc
	// virtual destructor will do this
}

SheetAnimations_GameDevHelperAPI_RandomFrames::SheetAnimations_GameDevHelperAPI_RandomFrames()
{
}

CCScene* SheetAnimations_GameDevHelperAPI_RandomFrames::scene()
{
	CCScene * scene = NULL;
	do
	{
		// 'scene' is an autorelease object
		scene = CCScene::create();
		CC_BREAK_IF(! scene);
        
		// 'layer' is an autorelease object
		SheetAnimations_GameDevHelperAPI_RandomFrames *layer = SheetAnimations_GameDevHelperAPI_RandomFrames::create();
		CC_BREAK_IF(! layer);
        
		// add layer as a child to scene
		scene->addChild(layer);
	} while (0);
    
	// return the scene
	return scene;
}

std::string SheetAnimations_GameDevHelperAPI_RandomFrames::initTest()
{
    
    CCSize s = CCDirector::sharedDirector()->getWinSize();
    
#if 1
    // Use batch node. Faster
    //when using batches - load a batch node using the generated image
    batchNodeParent = CCSpriteBatchNode::create("spriteSheetAnimationsTest_flames.png", 100);
    this->addChild(batchNodeParent, 0);
#endif
    CCSpriteFrameCache::sharedSpriteFrameCache()->removeUnusedSpriteFrames();
    
    //load into the sprite frame cache the plist generated by SH
    CCSpriteFrameCache::sharedSpriteFrameCache()->addSpriteFramesWithFile("spriteSheetAnimationsTest_flames.plist");
    
    
    //using the GameDevHelper API animation cache - this will create GHAnimation objects - which are more complex then cocos2dx animations
    GHAnimationCache *cache = GHAnimationCache::sharedAnimationCache();
    cache->addAnimationsWithFile("spriteSheetAnimationsTest_SheetAnimations.plist");//the animation exported plist file
    
    this->executeTestCodeAtPosition(ccp(s.width/2, s.height/2));
    
    return "GameDevHelperAPI animations. Demonstrate random frames.\nThe left flames will play normally, while the right flames\nplay using random frames giving a more realistic look.\n";
}

void SheetAnimations_GameDevHelperAPI_RandomFrames::executeTestCodeAtPosition(CCPoint p)
{

    {
        //loading the sprite that will run the animation with random restart time
        GHSprite * spriteRandom = GHSprite::createWithSpriteFrameName("flame0.png");//the name of one of the sprite in the sheet plist
        
        if(batchNodeParent != NULL){//if we use batch nodes we must add the sprite to its batch parent
            batchNodeParent->addChild(spriteRandom);
        }
        else{//if we dont use batch nodes then we must add the sprite to a normal node - e.g the layer or another node
            this->addChild(spriteRandom);
        }
        spriteRandom->setPosition(ccp(p.x + 60, p.y - 60));
        spriteRandom->setScale(2);
        
        GHAnimationCache *cache = GHAnimationCache::sharedAnimationCache();
        GHAnimation *animation = cache->animationByName("fireAnim");//the name of the animation
        
        spriteRandom->prepareAnimation(animation);
        spriteRandom->playAnimation();
        
        //spriteRandom->setAnimationDelegate(this);
    }
    
    {
        //loading the sprite that will run the animation with random restart time
        GHSprite * spriteRandom = GHSprite::createWithSpriteFrameName("flame0.png");//the name of one of the sprite in the sheet plist
        
        if(batchNodeParent != NULL){//if we use batch nodes we must add the sprite to its batch parent
            batchNodeParent->addChild(spriteRandom);
        }
        else{//if we dont use batch nodes then we must add the sprite to a normal node - e.g the layer or another node
            this->addChild(spriteRandom);
        }
        
        spriteRandom->setPosition(ccp(p.x + 60, p.y + 60));
        spriteRandom->setScale(2);
        
        GHAnimationCache *cache = GHAnimationCache::sharedAnimationCache();
        GHAnimation *animation = cache->animationByName("fireAnim");//the name of the animation
        
        spriteRandom->prepareAnimation(animation);
        spriteRandom->playAnimation();
        
        //spriteRandom->setAnimationDelegate(this);
    }
    
    
    
    
    {
        //loading the sprite that will run the animation normal
        GHSprite * sprite = GHSprite::createWithSpriteFrameName("flame0.png");//the name of one of the sprite in the sheet plist
        
        if(batchNodeParent != NULL){//if we use batch nodes we must add the sprite to its batch parent
            batchNodeParent->addChild(sprite);
        }
        else{//if we dont use batch nodes then we must add the sprite to a normal node - e.g the layer or another node
            this->addChild(sprite);
        }

        sprite->setPosition(ccp(p.x - 60, p.y - 60));
        sprite->setScale(2);
        
        //this is another way you can prepare an animation on a sprite
        sprite->prepareAnimationWithName("fireAnim");
        sprite->getAnimation()->setRandomFrames(false);//MAKE RANDOM FRAMES FALSE - as this animation has random frames set to true (check SpriteHelper document)
        sprite->playAnimation();
    }
    
    {
        //loading the sprite that will run the animation normal
        GHSprite * sprite = GHSprite::createWithSpriteFrameName("flame0.png");//the name of one of the sprite in the sheet plist
        
        if(batchNodeParent != NULL){//if we use batch nodes we must add the sprite to its batch parent
            batchNodeParent->addChild(sprite);
        }
        else{//if we dont use batch nodes then we must add the sprite to a normal node - e.g the layer or another node
            this->addChild(sprite);
        }
        
        sprite->setPosition(ccp(p.x - 60, p.y + 60));
        sprite->setScale(2);
        
        
        //this is another way you can prepare an animation on a sprite
        sprite->prepareAnimationWithName("fireAnim");
        sprite->getAnimation()->setRandomFrames(false);//MAKE RANDOM FRAMES FALSE - as this animation has random frames set to true (check SpriteHelper document)
        sprite->playAnimation();
    }
    
}

void SheetAnimations_GameDevHelperAPI_RandomFrames::animationDidFinishPlayingOnSprite(GHAnimation* anim,
                                                                                          GHSprite* sprite){
    
    CCLog("Animation %s DID FINISH playing on sprite %s", anim->getName().c_str(), sprite->description().c_str());
}
void SheetAnimations_GameDevHelperAPI_RandomFrames::animationDidChangeFrameIdxOnSprite(GHAnimation* anim,
                                                                                           int frmIdx,
                                                                                           GHSprite* sprite){

    CCLog("Animation %s DID CHANGE FRAME %d on sprite %s", anim->getName().c_str(), frmIdx, sprite->description().c_str());
}
void SheetAnimations_GameDevHelperAPI_RandomFrames::animationDidFinishRepetitionOnSprite(GHAnimation* anim,
                                                                                             int repetitionNo,
                                                                                             GHSprite* sprite){
    
    CCLog("Animation %s DID FINISH REPETITION  %d on sprite %s", anim->getName().c_str(), repetitionNo, sprite->description().c_str());
    
}


